name: Build an ISO ( Actions Artifact )

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        environment: secrets 
        container:
            image: archlinux:latest
            options: --privileged
        steps:
            - uses: actions/checkout@v2
            - name: Prepare keyring
              run: |
                  pacman-key --init
                  pacman --noconfirm -Sy archlinux-keyring
                  echo cdn ${{ secrets.CDN_HOST }}
                  echo cdn ${{ secrets.CDN_CIUUID }}
            
            - name: Install tools
              run: |
                  rm /etc/pacman.conf
                  cp pacman.conf /etc/pacman.conf
                  pacman --noconfirm -Syyu
                  pacman --noconfirm -S archiso git jq
            
            - name: Build ISO
              run: |
                  mkarchiso -v .
        
            - name: Upload artifact
              uses: actions/upload-artifact@v4.6.2
              with:
                name: azuos-iso
                path: out/*.iso

    release:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
          - name: Download artifact
            uses: actions/download-artifact@v4
            with:
                name: azuos-iso
                path: . 

          - name: Draft a Github release
            uses: softprops/action-gh-release@v3.0.0
            with:
                tag_name: ${{ github.ref_name }}-${{ github.run_number }}
                body: "auto upload"
                draft: true
                prerelease: true
                make_latest: false
                files: ./*.iso
